### ISSUE TITLE
How to do heuristics only based on text not extension?

### ISSUE THREAD

**Issue by pvonmoradi** [monkslc/hyperpolyglot#10]
For example grab a C file, change its extension to `.go`. `github-linguist`, `enry` and `hyperpolyglot` detect it as a Go source.
If I remove the extension, `hyperpolyglot` returns empty.

**Comment by StringKe** [comment]
```toml
[dependencies]
hyperpolyglot = { git = "https://github.com/StringKe/hyperpolyglot.git", branch = "master" }
```

```rust
fn main() {
    let content = r#"
   use clipboard_rs::{ClipboardContext, ClipboardHandler};

pub struct ClipboardManager {
    ctx: ClipboardContext,
}

impl ClipboardManager {
    pub fn new() -> Self {
        Self {
            ctx: ClipboardContext::new().unwrap(),
        }
    }
}

impl ClipboardHandler for ClipboardManager {
    fn on_clipboard_change(&mut self) {
        println!("Clipboard changed");
    }
}
    "#;
    let result = hyperpolyglot::detectors::classify(content, &*vec![]);
    println!("{}", result.to_string());
}

```
